### ISSUE TITLE
Feature: production-destruction-rest systems

### ISSUE THREAD

**Issue by ranocha** [SKopecz/PositiveIntegrators.jl#43]
It would be great to support systems that are not necessarily conservative but have a conservative part (treated via the Patankar trick) and an additional part (integrated as usual in RK methods).

**Comment by ranocha** [comment]
I cam across this again. It would be nice if we could add additional (production) terms that are not weighted by the (modified) Patanker trick

**Comment by SKopecz** [comment]
If you use a `PDSProblem` you can put these terms on the diagonal of the production matrix `P`. Only the off-diagonal terms of `P` have corresponding destruction terms and will be weighted.

**Comment by ranocha** [comment]
I see, thanks. So the off-diagonal terms of the production matrix are used to setup the corresponding conservative production-destruction system, the diagonal terms are used as they are in the underlying Runge-Kutta method (and should be non-negative), and the destruction terms from the additional destruction vector are weighted by the Patankar trick 👍 
Do we have some tests for this setup?

**Comment by ranocha** [comment]
Thanks!
